const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..")
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"))

assert.equal(manifest.id, "io.github.patrickfanella.shelfish")
assert.equal(manifest.name, "Shelfish")
assert.equal(manifest.version, "1.1.0")
assert.equal(manifest.author, "Patrick Fanella")
assert.equal(manifest.license, "MIT")

for (const file of ["README.md", "LICENSE", "manifest.json", "I18n.js", "tests/i18n.test.js"])
  assert.equal(fs.statSync(path.join(root, file)).isFile(), true)

const sourceFiles = ["BarWidget.qml", "GroupButton.qml", "ManagePanel.qml", "SettingsButton.qml", "Service.qml", "Model.js", "I18n.js", "manifest.json", "README.md"]
const source = sourceFiles.map(file => fs.readFileSync(path.join(root, file), "utf8")).join("\n")
const service = fs.readFileSync(path.join(root, "Service.qml"), "utf8")
const barWidget = fs.readFileSync(path.join(root, "BarWidget.qml"), "utf8")
const groupButton = fs.readFileSync(path.join(root, "GroupButton.qml"), "utf8")
const managePanel = fs.readFileSync(path.join(root, "ManagePanel.qml"), "utf8")
const settingsButton = fs.readFileSync(path.join(root, "SettingsButton.qml"), "utf8")
assert.match(service, /groupPrefix: moduleName \+ "\.group\."/)
assert.match(source, /serviceFor\("io\.github\.patrickfanella\.shelfish"\)/)
assert.match(barWidget, /function close\(\)/)
assert.match(barWidget, /text: "\\uf1de"/)
assert.match(service, /import "I18n\.js" as I18n/)
assert.match(service, /readonly property string localeName: Qt\.locale\(\)\.name/)
assert.match(service, /function tr\(key, args\)/)
assert.match(barWidget, /tooltipText: root\.tr\("settings\.shortcut"\)/)
assert.match(settingsButton, /tooltipText: root\.tr\("settings\.shortcut"\)/)
assert.match(groupButton, /root\.tr\("group\.fallback"\)/)
assert.match(managePanel, /name: tr\("settings\.shortcut"\)/)
assert.match(managePanel, /model: \[root\.tr\("direction\.left"\), root\.tr\("direction\.right"\)\]/)
assert.match(managePanel, /direction: direction\.currentIndex === 0 \? "left" : "right"/)
assert.match(service, /shell\.mutateShellConfig\(function\(shellConfig\)/)
assert.match(service, /Model\.removeGeneratedEntries\(layout, root\.groupPrefix\)/)
assert.match(service, /property bool suspended: false/)
assert.match(service, /function showGroup\(id\) \{[\s\S]*?revealTimer\.stop\(\)/)
assert.match(service, /function canToggleGroups\(\)/)
assert.match(barWidget, /service\.suppressGroupToggles\(\)/)
assert.match(groupButton, /root\.service\.canToggleGroups\(\)/)
assert.match(source, /memberEntries\[id\]\.push\(source\[i\]\)/)
assert.match(managePanel, /^KeyboardPanel \{/m)
assert.match(managePanel, /focusTarget: newGroupName/)
assert.match(managePanel, /textFormat: Text\.PlainText/g)
assert.match(source, /candidate\.length > 2048/)
assert.match(source, /value\.slice\(0, 256\)/)
assert.match(managePanel, /shelfish\.settings/)
assert.match(settingsButton, /root\.service\.manage\(\)/)

console.log("release tests passed")
